# Generated by Django 4.2.7 on 2024-05-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='dueño',
            new_name='propietario',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='id_hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cantidad_habitaciones',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='precio',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Anfitrion'), (3, 'Cliente'), (4, 'Moderador')], default=3),
        ),
        migrations.CreateModel(
            name='PisosHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_piso', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_piso_hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='planning_travel.pisoshotel'),
            preserve_default=False,
        ),
    ]
