# Generated by Django 5.0b1 on 2024-05-14 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0002_rename_dueño_hotel_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='fecha_agregado',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
