# Generated by Django 5.0b1 on 2024-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0003_alter_favorito_fecha_agregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='token_recuperar',
            field=models.CharField(default=1, max_length=254),
        ),
    ]
