# Generated by Django 5.0b1 on 2024-05-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0007_remove_favorito_token_recuperar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='token_recuperar',
        ),
    ]
