# Generated by Django 5.0b1 on 2024-05-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0008_remove_hotel_token_recuperar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.IntegerField(choices=[(1, 'Tarjeta de credito'), (2, 'Tarjeta debito'), (3, 'Efectivo')])),
                ('numero_tarjeta', models.CharField(blank=True, max_length=30, null=True)),
                ('caducidad', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_cvv', models.CharField(blank=True, max_length=5, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
