# Generated by Django 5.0b1 on 2024-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_travel', '0009_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservausuario',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'reservada'), (2, 'libre'), (3, 'cancelada')], default=1),
        ),
        migrations.AlterField(
            model_name='reservausuario',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
